### ISSUE TITLE
:not() ?

### ISSUE THREAD

**Issue by greg-minshall** [coderobe/hq#4]
hi.  thanks for this utility.

i'm trying to use the `:not()` pseudo-class, but either i'm using it incorrectly, i misunderstand how it works, or it isn't working.  (i'm basicaly looking for a `grep -v` version, to produce a .html file that does *not* have a given element.)

`1218`, the "positive" version, is the typical use, and works fine.  `1219`, still "positive", makes me think i don't understand -- why are things duplicated?  `1220` and `1221` are the negative form, but `<div>s` still appear on the output.

```
bash apollo2 (master): {1218} echo '<div>this is a test</div><a href=foo.com>' | hq 'div' data
<div>this is a test</div>

bash apollo2 (master): {1219} echo '<div>this is a test</div><a href=foo.com>' | hq '*' data
<html><head></head><body><div>this is a test</div><a href="foo.com">
</a></body></html>
<head></head>
<body><div>this is a test</div><a href="foo.com">
</a></body>
<div>this is a test</div>
<a href="foo.com">
</a>

bash apollo2 (master): {1220} echo '<div>this is a test</div><a href=foo.com>' | hq '*:not(div)' data
<html><head></head><body><div>this is a test</div><a href="foo.com">
</a></body></html>
<head></head>
<body><div>this is a test</div><a href="foo.com">
</a></body>
<a href="foo.com">
</a>

bash apollo2 (master): {1221} echo '<div>this is a test</div><a href=foo.com>' | hq ':not(div)' data
<html><head></head><body><div>this is a test</div><a href="foo.com">
</a></body></html>
<head></head>
<body><div>this is a test</div><a href="foo.com">
</a></body>
<a href="foo.com">
</a>
```

**Comment by coderobe** [comment]
As far as your supplied CSS selector is concerned, the output is correct - in
```
echo '<div>this is a test</div><a href=foo.com>' | hq '*:not(div)' data
<html><head></head><body><div>this is a test</div><a href="foo.com">
</a></body></html>
<head></head>
<body><div>this is a test</div><a href="foo.com">
</a></body>
<a href="foo.com">
</a>
```
what you're actually getting is 4 elements worth of raw html, the first one being the implicit `<html>` and its contents, then the implicit `<head>` and its content, then the implicit `<body>` and its content, and your `<a>`, those elements are all `:not(div)`. 

The reason you're seeing your div in the output is because the `html` and `body` tags all contain your div somewhere inside, by nature of your div being implicitly inside of `body` and `body` implicitly being inside of `html`  

Rendering your example HTML using chromium, its CSS selector engine agrees with hq's results:
![image](https://user-images.githubusercontent.com/8442384/107709624-cc7c7e00-6cc5-11eb-9a19-6462ebfa7f03.png)

**Comment by coderobe** [comment]
You'd want a more specific selector that does not match any (implicit or not) nodes leading up to your element, i.e. `echo '<div>this is a test</div><a href=foo.com>' | hq 'body :not(div)' data`

**Comment by greg-minshall** [comment]
ah.  thanks!  sorry for forcing a tutorial!  i should have tried it in a browser -- that's also good technique i'm glad i learned.

and, again, thanks for hq(1)!
